import { hardwareImages } from "@/lib/hardware-images";
import type { ShopProduct } from "@/types/shop";

/** Sample catalogue for preview when Supabase is not connected. */
export const DEMO_INVENTORY: ShopProduct[] = [
  {
    id: "demo-hammer",
    item_name: "Claw Hammer 16oz",
    item_code: "TL-HAM-16",
    description: "Drop-forged steel head with fibreglass handle",
    category: "Hand Tools",
    quantity: 48,
    unit_price: 12.5,
    image_url: hardwareImages.toolbox,
  },
  {
    id: "demo-drill",
    item_name: "Cordless Drill 18V",
    item_code: "PW-DRL-18",
    description: "Brushless motor, 2-speed gearbox, includes battery",
    category: "Power Tools",
    quantity: 22,
    unit_price: 189.0,
    image_url: hardwareImages.drillLumber,
  },
  {
    id: "demo-socket",
    item_name: "Socket Set 32pc",
    item_code: "TL-SKT-32",
    description: "Metric & imperial, chrome vanadium",
    category: "Hand Tools",
    quantity: 15,
    unit_price: 45.0,
    image_url: hardwareImages.socketSet,
  },
  {
    id: "demo-cement",
    item_name: "Portland Cement 50kg",
    item_code: "BM-CEM-50",
    description: "General-purpose cement for concrete and mortar",
    category: "Building Materials",
    quantity: 120,
    unit_price: 11.75,
    image_url: hardwareImages.drillLumber,
  },
  {
    id: "demo-screws",
    item_name: "Wood Screws Assorted Box",
    item_code: "BM-SCR-BOX",
    description: "Mixed sizes, zinc-plated",
    category: "Fasteners",
    quantity: 60,
    unit_price: 8.5,
    image_url: hardwareImages.screwsOrganizer,
  },
  {
    id: "demo-pvc",
    item_name: "PVC Pipe 110mm x 6m",
    item_code: "PL-PVC-110",
    description: "Pressure pipe for drainage and sewer",
    category: "Plumbing",
    quantity: 35,
    unit_price: 24.0,
    image_url: hardwareImages.plumbingInstall,
  },
  {
    id: "demo-tap",
    item_name: "Basin Mixer Tap Chrome",
    item_code: "PL-TAP-BAS",
    description: "Single-lever basin mixer, ceramic cartridge",
    category: "Plumbing",
    quantity: 18,
    unit_price: 32.0,
    image_url: hardwareImages.plumbingFixtures,
  },
  {
    id: "demo-cable",
    item_name: "Twin & Earth Cable 2.5mm 100m",
    item_code: "EL-CBL-25",
    description: "House wiring cable, 450/750V",
    category: "Electrical",
    quantity: 25,
    unit_price: 95.0,
    image_url: hardwareImages.powerToolsBench,
  },
  {
    id: "demo-switch",
    item_name: "Double Socket Outlet",
    item_code: "EL-SKT-2G",
    description: "13A switched socket, white",
    category: "Electrical",
    quantity: 80,
    unit_price: 4.25,
    image_url: hardwareImages.powerToolsBench,
  },
  {
    id: "demo-paint",
    item_name: "Interior Emulsion 20L",
    item_code: "PT-EMU-20",
    description: "Matt finish, washable, brilliant white",
    category: "Paint",
    quantity: 40,
    unit_price: 58.0,
    image_url: hardwareImages.paintCansWood,
  },
  {
    id: "demo-brush",
    item_name: "Paint Brush Set 5pc",
    item_code: "PT-BRS-5",
    description: "Synthetic bristles for water- and oil-based paints",
    category: "Paint",
    quantity: 55,
    unit_price: 14.0,
    image_url: hardwareImages.paintSupplies,
  },
  {
    id: "demo-hose",
    item_name: "Garden Hose 30m",
    item_code: "GD-HOS-30",
    description: "Reinforced PVC, kink-resistant",
    category: "Garden",
    quantity: 28,
    unit_price: 36.0,
    image_url: hardwareImages.toolBag,
  },
  {
    id: "demo-lock",
    item_name: "Mortice Lock Set",
    item_code: "BM-LCK-MOR",
    description: "5-lever deadlock with keys",
    category: "Door Hardware",
    quantity: 32,
    unit_price: 28.5,
    image_url: hardwareImages.doorLocks,
  },
  {
    id: "demo-ratchet",
    item_name: "Ratchet Spanner Set 12pc",
    item_code: "TL-RCH-12",
    description: "Chrome finish, metric sizes",
    category: "Hand Tools",
    quantity: 20,
    unit_price: 52.0,
    image_url: hardwareImages.ratchetsAisle,
  },
  {
    id: "demo-clamp",
    item_name: "G-Clamp 150mm",
    item_code: "TL-CLP-150",
    description: "Cast iron frame, swivel pad",
    category: "Tools",
    quantity: 44,
    unit_price: 9.75,
    image_url: hardwareImages.workshopClamps,
  },
];
