import type { ShopProduct } from "@/types/shop";
import { resolveDepartmentId, STORE_DEPARTMENTS } from "@/lib/catalog-departments";

/** Typical products customers can find in each department aisle. */
export const DEPARTMENT_ITEM_LISTS: Record<string, string[]> = {
  tools: [
    "Angle grinders",
    "Bench grinders",
    "Chisels & punches",
    "Clamps (G, F, bar)",
    "Cordless drill kits",
    "Drill bits (HSS, masonry, wood)",
    "Extension leads & reels",
    "Files & rasps",
    "Hammer drills",
    "Hammers (claw, ball pein, sledge)",
    "Hand saws & hacksaws",
    "Impact drivers & wrenches",
    "Jigsaws & reciprocating saws",
    "Levels (spirit, laser)",
    "Measuring tapes & rulers",
    "Multi-tools",
    "Nail guns & staples",
    "Pliers (combination, long nose, locking)",
    "Power tool batteries & chargers",
    "Router bits & routers",
    "Safety glasses & ear protection",
    "Sanders (orbital, belt)",
    "Screwdriver sets",
    "Socket sets & ratchets",
    "Spirit levels & squares",
    "Staple guns",
    "Tool boxes & bags",
    "Tool belts & pouches",
    "Torches & work lights",
    "Vices & workbenches",
    "Welding rods & accessories",
    "Wrenches (adjustable, ring, open)",
  ],
  building: [
    "Aggregates & sand",
    "Bolts, nuts & washers",
    "Bricks & blocks",
    "Cement & mortar",
    "Door handles & locks",
    "Door hinges",
    "Drywall & plasterboard",
    "Galvanized sheeting",
    "Hinges & brackets",
    "Insulation boards",
    "Lumber & timber",
    "Masonry anchors",
    "Nails (wire, clout, framing)",
    "Plywood & chipboard",
    "PVC & guttering",
    "Roofing sheets & tiles",
    "Screws (wood, drywall, self-tapping)",
    "Sealants & construction adhesive",
    "Steel angles & flat bar",
    "Tarps & builders plastic",
    "Treated poles & decking",
    "Wall plugs & anchors",
    "Window frames & putty",
    "Wire mesh & rebar",
  ],
  plumbing: [
    "Basins & pedestals",
    "Bath taps & mixers",
    "Baths & shower trays",
    "Cisterns & flush mechanisms",
    "Drain cleaners",
    "Geyser elements & thermostats",
    "Geysers (water heaters)",
    "Kitchen sinks",
    "Pipe cutters & wrenches",
    "Pipe insulation",
    "Plumbing tape (PTFE)",
    "PVC cement & primer",
    "PVC elbows, tees & couplings",
    "PVC pipe (½\", ¾\", 1\")",
    "Shower heads & rails",
    "Shower mixers",
    "Sink traps & waste",
    "Stopcocks & isolating valves",
    "Toilet pans & seats",
    "Toilet repair kits",
    "Washers & O-rings",
    "Water filters",
    "Water pumps",
  ],
  electrical: [
    "Batteries (AA, AAA, 9V)",
    "Cable ties",
    "Ceiling roses & pendants",
    "Circuit breakers (MCBs)",
    "Conduit & trunking",
    "Distribution boards",
    "Electrical tape",
    "Extension cords",
    "Fuses & fuse holders",
    "Generators",
    "Junction boxes",
    "LED bulbs & tubes",
    "Light fittings & battens",
    "Multimeters & testers",
    "Plugs & adaptors",
    "RCDs & safety switches",
    "Solar panels & inverters",
    "Switches (1-gang, 2-gang)",
    "Twin & earth cable",
    "Wall sockets (single, double)",
    "Wire strippers & crimpers",
  ],
  paint: [
    "Acrylic & PVA paint",
    "Brushes (all sizes)",
    "Caulking guns",
    "Drop sheets & masking tape",
    "Enamel & gloss paint",
    "Exterior weatherproof paint",
    "Fillers & putty",
    "Paint rollers & sleeves",
    "Paint trays & liners",
    "Primers & undercoats",
    "Roof paint",
    "Sandpaper & sanding blocks",
    "Spray paint",
    "Stains & varnishes",
    "Thinners & turpentine",
    "Tile adhesive & grout",
    "Wallpaper & paste",
    "Wood preservatives",
  ],
  garden: [
    "Axes & mauls",
    "Compost & potting soil",
    "Fertilizers",
    "Garden forks & spades",
    "Garden hose & fittings",
    "Garden rakes",
    "Hand trowels & cultivators",
    "Hedge trimmers",
    "Irrigation sprinklers",
    "Lawn mowers",
    "Leaf blowers",
    "Outdoor extension leads",
    "Plant pots & trays",
    "Pruners & loppers",
    "Secateurs",
    "Shovels & picks",
    "Sprayers & watering cans",
    "String trimmers",
    "Wheelbarrows",
    "Wire fencing & posts",
  ],
};

export function productBelongsToDepartment(product: ShopProduct, departmentId: string): boolean {
  const haystack = [product.category, product.item_name, product.description ?? ""]
    .join(" ")
    .toLowerCase();
  const dept = STORE_DEPARTMENTS.find((d) => d.id === departmentId);
  if (!dept) return false;
  if (resolveDepartmentId(product.category) === departmentId) return true;
  return dept.categoryMatchers.some((m) => haystack.includes(m));
}

export function getDepartmentInventory(
  products: ShopProduct[],
  departmentId: string
): ShopProduct[] {
  return products
    .filter((p) => productBelongsToDepartment(p, departmentId))
    .sort((a, b) => a.item_name.localeCompare(b.item_name));
}

export function getDepartmentItemList(departmentId: string): string[] {
  return DEPARTMENT_ITEM_LISTS[departmentId] ?? [];
}
