// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { getSupabaseConfig, isSupabaseConfigured } from "@/lib/supabase-env";

const { url, key } = getSupabaseConfig();

/** Valid-looking placeholders so createClient never throws at import (blank screen on Render). */
const FALLBACK_URL = "https://placeholder.supabase.co";
const FALLBACK_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsYWNlaG9sZGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NDUxOTI4MDAsImV4cCI6MTk2MDc2ODgwMH0.placeholder";

const configured = isSupabaseConfigured();

if (!configured) {
  console.info(
    "[NAVIRA] Running in preview mode — Supabase env vars not set. Browse and sample products work; auth and orders are disabled."
  );
}

export const supabase = createClient<Database>(
  configured ? url : FALLBACK_URL,
  configured ? key : FALLBACK_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

export { isSupabaseConfigured };
